# Generated by Django 5.0.6 on 2024-06-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinventory',
            options={'verbose_name_plural': 'DeviceInventory'},
        ),
        migrations.AlterModelOptions(
            name='maininventory',
            options={'verbose_name_plural': 'MainInventory'},
        ),
    ]
