# Generated by Django 5.0.6 on 2024-06-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_deviceinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maininventory',
            options={},
        ),
    ]
