# Generated by Django 5.0.6 on 2024-06-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_deviceinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinventory',
            name='type',
            field=models.CharField(default='DefaultType', max_length=50),
        ),
        migrations.AlterModelOptions(
            name='deviceinventory',
            options={'verbose_name_plural': 'DeviceInventory'},
        ),
        migrations.AlterModelOptions(
            name='maininventory',
            options={'verbose_name_plural': 'MainInventory'},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
