# Generated by Django 5.0.6 on 2024-06-20 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_deviceinventory_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinventory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='status',
        ),
        migrations.AddField(
            model_name='maininventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
