# Generated by Django 5.0.6 on 2024-06-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_deviceinventory_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinventory',
            name='user',
        ),
    ]
