# Generated by Django 5.0.6 on 2024-06-20 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_deviceinventory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininventory',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maininventory_name', to='inventory.deviceinventory'),
        ),
        migrations.AlterField(
            model_name='maininventory',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maininventory_type', to='inventory.deviceinventory'),
        ),
    ]
